### ISSUE TITLE
concurrent write to the db

### ISSUE THREAD

**Issue by PavelPolyakov** [hapijs/catbox-mongodb#13]
Hi,

Copying the issue from here:
https://github.com/hapijs/yar/issues/73#issuecomment-107556267

@Selvatico

>Hello to all,

>So problem is next - we have several workers in cluster. 2 of them receive requests almost at the same time - each of them read session storage (MongoDB in our case). In parallel they are finishing their work and save all values of from session

>~~~
>request.session._store
>~~~

>to cache storage. And one of them override value of another, because both of them doesn't see changes of another and dump all data to storage. I'm wondering if exist some technics to avoid such behavior using yar ? Because from my point of view - we should implement in yar some atomic updates, but it should be implemented in *catbox* adapters too, which requires too much changes in core of Hapi.

Any thoughts?

Regards,

**Comment by jardakotesovec** [comment]
I think this use case is beyond catbox purpose. Catbox is caching layer - not layer for exchanging data. 

So lets say you have one request which is for some reason handled by two workers - since its same request resulting in same key in cache - they both should generate same data, so writing this twice should not be problem.  Thats is assumption for caching. Does it make sense?

Maybe you could describe your use case in more details on (discuss)[github.com/hapijs/discuss] repo to get some ideas from others how you could approach it.

**Comment by PavelPolyakov** [comment]
@jardakotesovec 
It makes sense, but, even we use cache logic.

Assuming you have key A and object A.
Request 1: writes A->B->C->D nested cache value
Request 2: writes A->B->E->F nested cache value

And only one would be stored in the database at the end. So we've cached only a half of the information, while both of our requests were trying to update the one cache root key.

**Comment by jardakotesovec** [comment]
You are still trying to save different values for same key in your use case- which is not usual caching workflow. I think that the confusion is caused because yar is used together with catbox, which does not server well your purpose as you want to use it more like proper storage than just caching layer.... 

With catbox (caching) - when request comes catbox checks the cache and if cached value is not there it will get the data from database or some other request etc..  not from the cache itself. Once it gets value it sends it back to user and also to catbox so its prepared for next time.  So when this happen concurrently - two workers just get (computer/fetch/whatever) value and both save it to database - so its saved twice, and again the result of these request should be same and saved value should be same - otherwise does not make sense to cache it.

Hopefully I am explaining this properly..   it was long day :-).

So I think you need to implement your own session database storage where you could consider the fact that you want to somehow merge the written data or you want to write data again if data has changed since you read them.  Generally this is pain to do in mongodb..  because there are no transactions - so you have to implement something on (app level)[http://docs.mongodb.org/manual/tutorial/update-if-current/]. 

Absence of transaction is actually one of the reasons why I don't use mongodb much anymore...  MongoDB definitely has its use cases..  but in many cases its pain in the ass.

**Comment by PavelPolyakov** [comment]
@jardakotesovec 
Thanks!
